const domains=["Lower Body Strength","Upper Body Strength","Core Control","Mobility and Balance","Cardio Conditioning","Full-Body Patterns"];
const D=domains;
function E(name,domain,difficulty,pattern,protect,targets,benefits,description,instructions,cues,easier,harder){return{name,domain,difficulty,pattern,protect,targets,benefits,description,instructions,cues,mistakes:["Moving too fast","Forcing range","Ignoring discomfort"],easier,harder};}
const exercises=[
E("Bodyweight Squat",D[0],"Starter","squat",[],["quads","glutes","hips","core"],"Builds lower-body strength for sitting, standing and stairs.","A controlled hip-and-knee bending pattern.",["Stand with feet hip to shoulder width.","Send hips back and bend knees.","Keep knees tracking over toes.","Press through the whole foot to stand."],["Slow descent","Chest open","Breathe steadily"],"Sit-to-stand from a chair.","Pause two seconds at the bottom."),
E("Sit-to-Stand Flow",D[0],"Starter","squat",[],["quads","glutes","balance"],"Practical strength for chair transfers and daily function.","A chair-supported squat variation.",["Sit near the front of a stable chair.","Place feet flat.","Lean slightly forward and stand.","Sit back down with control."],["Nose over toes","Control the sitting phase","Use hands only if needed"],"Use a higher chair.","Hover briefly above the chair."),
E("Reverse Lunge",D[0],"Building","lunge",["knee"],["glutes","quads","hips","balance"],"Trains single-leg strength and balance.","A step-back lunge with controlled depth.",["Stand tall.","Step one foot back.","Bend both knees slightly.","Push through the front foot to return."],["Short range is fine","Front knee aligned","Use a wall for balance"],"Step-back tap only.","Slow three-count lowering."),
E("Glute Bridge",D[0],"Starter","bridge",[],["glutes","hamstrings","hips","trunk"],"Supports hip extension strength for walking and posture.","A floor-based hip lift pattern.",["Lie on your back with knees bent.","Brace gently.","Press through heels and lift hips.","Lower with control."],["Ribs quiet","Squeeze glutes","Do not arch the back"],"Half bridge.","Single-leg bridge hold."),
E("Wall Sit",D[0],"Building","squat",["knee"],["quads","glutes","endurance"],"Builds lower-body endurance with support.","A supported lower-body hold against a wall.",["Stand with back against a wall.","Walk feet forward.","Slide down only as far as comfortable.","Hold and breathe."],["Pain-free angle","Knees over ankles","Stop before form breaks"],"Stay higher on the wall.","Hold longer or add heel raises."),
E("Calf Raise",D[0],"Starter","calf",[],["calves","ankles","balance"],"Supports ankle strength and walking push-off.","A simple ankle-strengthening pattern near support.",["Stand near a wall or chair.","Rise onto the balls of your feet.","Pause briefly.","Lower slowly."],["Use support","Move evenly","Control the lowering"],"Use both hands on support.","Single-leg with support."),
E("Incline Push-Up",D[1],"Starter","push",["wrist","shoulder"],["chest","shoulders","triceps","core"],"Builds pushing strength with adjustable load.","A push-up using a wall, table or bench height.",["Place hands on a stable surface.","Step feet back.","Lower chest toward the surface.","Press back up."],["Higher is easier","Shoulders relaxed","Brace lightly"],"Wall push-up.","Lower the surface."),
E("Knee Push-Up",D[1],"Building","push",["wrist","shoulder"],["chest","triceps","shoulders","core"],"Builds upper-body pushing strength with reduced load.","A floor push-up from the knees.",["Hands under shoulders.","Create a long line from knees to head.","Lower with control.","Press back up."],["Neck long","Hips steady","Stop before shoulder discomfort"],"Incline push-up.","Full push-up negative."),
E("Pike Push-Up",D[1],"Confident","push",["wrist","shoulder"],["shoulders","triceps","upper back"],"Builds shoulder strength without equipment.","An overhead-press-like push-up from a hips-high position.",["Start with hips raised.","Bend elbows slowly.","Lower head slightly.","Press back up."],["Small range","Spread fingers","Move slowly"],"Incline pike push-up.","Slow eccentric pike push-up."),
E("Prone Y Raise",D[1],"Starter","row",["shoulder"],["upper back","shoulders","posture"],"Strengthens upper-back control.","A floor-based shoulder and upper-back activation drill.",["Lie face down.","Set arms in a Y shape.","Lift arms gently.","Lower slowly."],["Thumbs up","Neck relaxed","Small lift"],"One arm at a time.","Pause at the top."),
E("Scapular Push-Up",D[1],"Building","plank",["wrist","shoulder"],["shoulder blades","serratus anterior","core"],"Improves shoulder blade control.","A small shoulder-blade movement with straight elbows.",["Start on hands and knees or plank.","Keep elbows straight.","Let chest sink slightly.","Push the floor away."],["Small motion","No elbow bend","Use knees if needed"],"Hands-and-knees version.","Full plank version."),
E("Bear Shoulder Tap",D[1],"Confident","plank",["wrist","shoulder","back"],["shoulders","core","hips"],"Builds shoulder stability and anti-rotation control.","A hover position with alternating shoulder taps.",["Start on hands and knees.","Lift knees slightly.","Tap one shoulder with the opposite hand.","Alternate slowly."],["Widen base","Slow beats fast","Keep hips steady"],"Knees on floor.","Pause each tap."),
E("Forearm Plank",D[2],"Building","plank",["shoulder","back"],["core","shoulders","glutes"],"Builds trunk endurance for posture and control.","A static core hold supported on forearms.",["Place forearms on the floor.","Step feet back or use knees.","Make a long body line.","Hold while breathing."],["Ribs down","Glutes lightly on","Stop before form breaks"],"Knee forearm plank.","Longer hold."),
E("Dead Bug",D[2],"Starter","deadbug",["back"],["deep core","hips","coordination"],"Teaches trunk control while limbs move.","A floor exercise using opposite arm and leg movement.",["Lie on back with arms up.","Bring knees over hips.","Lower opposite arm and leg.","Return and switch."],["Small range first","Back comfortable","Slow motion"],"Move arms only.","Extend legs farther."),
E("Side Plank",D[2],"Building","plank",["shoulder"],["obliques","shoulders","hips"],"Builds lateral trunk strength and hip stability.","A side-supported trunk hold from knees or feet.",["Lie on one side.","Place forearm under shoulder.","Lift hips.","Hold and breathe."],["Push floor away","Hips stacked","Use knee version first"],"Bent-knee side plank.","Top-leg lift."),
E("Bird Dog",D[2],"Starter","balance",["back","wrist"],["core","glutes","back control"],"Improves cross-body coordination and trunk stability.","A hands-and-knees reach pattern.",["Start on hands and knees.","Reach opposite arm and leg.","Pause without twisting.","Return and switch."],["Reach long","Keep hips square","Use fists if wrists prefer"],"Leg-only reach.","Elbow-to-knee return."),
E("Hollow Hold Prep",D[2],"Confident","deadbug",["back"],["front core","hip flexors","trunk control"],"Develops anterior core control.","A controlled supine hold with adjustable limb position.",["Lie on back.","Bring knees over hips.","Press ribs down gently.","Extend limbs only as controlled."],["Bend knees to reduce load","Quality over duration","Stop if back arches"],"Dead bug hold.","Longer lever hold."),
E("Slow Mountain Climber",D[2],"Building","plank",["wrist","shoulder","back"],["core","hip flexors","shoulders"],"Builds trunk control while legs move.","A controlled plank knee-drive pattern.",["Start in plank or incline plank.","Draw one knee toward chest.","Return foot quietly.","Alternate sides."],["Use incline","Keep hips steady","Slow is the goal"],"Incline version.","Pause knee near chest."),
E("World’s Greatest Stretch",D[3],"Building","stretch",["wrist","knee"],["hips","spine","hamstrings","chest"],"Combines hip mobility, rotation and hamstring length.","A dynamic mobility sequence.",["Step into a comfortable lunge.","Place hands near the front foot.","Rotate chest gently.","Shift hips back slightly."],["Use small range","Move with breath","Pad the knee"],"Hands on chair.","Longer pause."),
E("Single-Leg Balance",D[3],"Starter","balance",[],["ankles","hips","balance"],"Improves balance confidence and ankle-hip control.","A simple standing balance drill near support.",["Stand near a wall or chair.","Lift one foot slightly.","Hold tall posture.","Switch sides."],["Use support","Soft knee","Focus eyes"],"Toe lightly on floor.","Turn head slowly with support."),
E("Hip Hinge Drill",D[3],"Starter","stretch",["back"],["hips","hamstrings","back control"],"Teaches safe bending mechanics.","A controlled hip-back movement pattern.",["Stand tall with hands on hips.","Push hips back.","Keep spine long.","Return by squeezing glutes."],["Hips back first","Knees soft","Small range"],"Practice facing a wall.","Kickstand hinge."),
E("Cat-Cow",D[3],"Starter","stretch",["wrist"],["spine","breathing","shoulders"],"Promotes gentle spinal mobility.","A slow spinal flexion-extension movement.",["Start on hands and knees.","Round the spine gently.","Arch gently.","Move comfortably."],["No forcing","Move slowly","Use forearms if wrists prefer"],"Seated cat-cow.","Add side-to-side rib movement."),
E("Ankle Rocker",D[3],"Starter","calf",["knee"],["ankles","calves","squat mechanics"],"Improves ankle mobility for squatting and walking.","A gentle forward-back ankle mobility drill.",["Stand in split stance near support.","Bend front knee toward toes.","Keep heel down.","Rock back and repeat."],["Heel heavy","Pain-free","Use support"],"Smaller knee movement.","Pause at end range."),
E("Thoracic Rotation",D[3],"Starter","stretch",["shoulder"],["upper back","chest","breathing"],"Supports upper-back mobility.","A controlled rotation drill.",["Start hands-and-knees or side-lying.","Place one hand behind head or across chest.","Rotate gently.","Return slowly."],["Rotate through ribs","Easy range","Follow hand with eyes if comfortable"],"Side-lying open book.","Longer pause."),
E("Low-Impact Jumping Jack",D[4],"Starter","cardio",["knee"],["heart-lung fitness","hips","shoulders"],"Raises heart rate without jumping.","A step-out version of a jumping jack.",["Stand tall.","Step one foot to the side.","Reach arms comfortably.","Return and switch."],["Stay low-impact","Breathe steadily","Reduce arm height if needed"],"Side step only.","Increase tempo gradually."),
E("March in Place",D[4],"Starter","cardio",[],["cardio","hips","coordination"],"Simple conditioning that scales easily.","A standing march with comfortable arm swing.",["Stand tall.","Lift one knee then the other.","Swing arms naturally.","Keep breathing easy."],["Talk-test pace","Use support if needed","Safe surface"],"Seated march.","Higher knees."),
E("Step Jack",D[4],"Starter","cardio",["knee"],["cardio","hips","shoulders"],"Builds rhythm, coordination and gentle conditioning.","Alternating side steps with optional arms.",["Step right foot out.","Bring left foot in.","Repeat to the other side.","Add arms when comfortable."],["Light feet","Smooth rhythm","Stay in control"],"Hands on hips.","Higher arm reach."),
E("Shadow Boxing",D[4],"Building","cardio",["shoulder"],["cardio","shoulders","coordination"],"Improves conditioning and coordination.","Controlled punching patterns in open space.",["Stand with soft knees.","Punch gently without locking elbows.","Alternate sides.","Keep shoulders relaxed."],["Loose hands","Turn torso slightly","Stay light"],"Punch lower and slower.","Add footwork."),
E("Skater Step",D[4],"Building","cardio",["knee"],["hips","cardio","lateral control"],"Trains side-to-side control and conditioning.","A low-impact lateral step pattern.",["Step to one side.","Tap the other foot behind.","Return to the other side.","Use arms for rhythm."],["Low impact","Knees aligned","Short steps first"],"Side step only.","Add a small hop if appropriate."),
E("Fast Feet Tap",D[4],"Confident","cardio",["knee"],["cardio","calves","coordination"],"Builds quickness and light-foot conditioning.","Small rapid steps in place.",["Stand with soft knees.","Take small quick steps.","Keep arms relaxed.","Use short intervals."],["Quiet feet","Short bursts","Stay tall"],"Slow march.","Longer interval."),
E("Burpee Walkout",D[5],"Building","burpee",["wrist","shoulder","back","knee"],["full body","cardio","core"],"Combines squat, plank and step-back control without jumping.","A lower-impact burpee variation.",["Squat or hinge to place hands down.","Step feet back one at a time.","Step feet forward.","Stand tall."],["Use table for incline","Step, do not jump","Pause if breathing rushes"],"Incline walkout.","Add a controlled push-up."),
E("Inchworm Walkout",D[5],"Building","inchworm",["wrist","shoulder","back"],["hamstrings","shoulders","core"],"Builds mobility and upper-body control.","A standing fold into a hand walkout.",["Start standing with soft knees.","Fold forward comfortably.","Walk hands to plank or incline.","Walk back and stand."],["Bend knees as needed","Short hand steps","Pain-free range"],"Hands on wall or table.","Add a plank hold."),
E("Squat to Reach",D[5],"Starter","squat",["knee","shoulder"],["legs","hips","shoulders","coordination"],"Links lower-body strength with reaching.","A squat followed by a comfortable reach.",["Perform a comfortable squat.","Stand and reach overhead or forward.","Lower arms.","Repeat smoothly."],["Comfortable reach","Control both phases","Stay balanced"],"Sit-to-stand with reach.","Pause at the bottom."),
E("Bear Crawl Hold",D[5],"Building","plank",["wrist","shoulder","back"],["core","shoulders","hips"],"Builds full-body tension and coordination.","A hands-and-knees hover.",["Start on hands and knees.","Lift knees slightly.","Hold while breathing.","Lower before form breaks."],["Small lift","Push the floor away","Short holds"],"Keep knees down.","Tiny forward/back steps."),
E("Plank to Down Dog",D[5],"Building","stretch",["wrist","shoulder"],["shoulders","hamstrings","core"],"Blends upper-body strength with mobility.","A controlled transition between plank and hips-high position.",["Start in plank or incline plank.","Push hips back and up.","Return to plank.","Move slowly."],["Bend knees","Spread fingers","Use incline"],"Hands on table.","Pause in each position."),
E("Cross-Crawl March",D[5],"Starter","cardio",[],["coordination","core","cardio"],"Trains cross-body coordination and gentle conditioning.","A standing march with opposite elbow-to-knee intention.",["Stand tall.","Lift one knee.","Bring opposite elbow toward it.","Alternate sides."],["Touch optional","Rotate gently","Stay tall"],"Hand to thigh.","Increase tempo gradually.")
];
const $=id=>document.getElementById(id);const state={selectedExercise:exercises[0],avatar:"neutral",currentPlan:[],logs:JSON.parse(localStorage.getItem("abc_logs")||"[]")};
function init(){D.forEach(d=>{const o=document.createElement("option");o.value=d;o.textContent=d;$("domainFilter").appendChild(o)});renderExercises();renderProgress();updateAvatar(exercises[0]);$("searchInput").addEventListener("input",renderExercises);$("domainFilter").addEventListener("change",renderExercises);$("coachForm").addEventListener("submit",handleCoachSubmit);$("logForm").addEventListener("submit",handleLogSubmit);$("exportLogBtn").addEventListener("click",exportLog);$("clearLogBtn").addEventListener("click",clearLog);$("copyPlanBtn").addEventListener("click",copyPlan);$("downloadPlanBtn").addEventListener("click",downloadPlan);["energyInput","sorenessInput"].forEach(id=>$(id).addEventListener("input",()=>{$("energyReadout").textContent=$("energyInput").value;$("sorenessReadout").textContent=$("sorenessInput").value}));bindAvatar("avatarNeutralBtn","neutral");bindAvatar("avatarMaleBtn","male");bindAvatar("avatarFemaleBtn","female")}
function bindAvatar(id,a){$(id).addEventListener("click",()=>{state.avatar=a;document.querySelectorAll(".seg").forEach(b=>b.classList.remove("active"));$(id).classList.add("active");updateAvatar(state.selectedExercise)})}
function updateAvatar(ex){state.selectedExercise=ex;$("avatarStage").className=`avatar-stage pattern-${ex.pattern} avatar-${state.avatar}`;$("demoName").textContent=ex.name;$("demoPattern").textContent=`${ex.pattern} pattern`}
function renderExercises(){const q=$("searchInput").value.trim().toLowerCase(),d=$("domainFilter").value,grid=$("exerciseGrid");grid.innerHTML="";const list=exercises.filter(ex=>{const s=[ex.name,ex.domain,ex.difficulty,ex.description,ex.benefits,ex.targets.join(" "),ex.cues.join(" ")].join(" ").toLowerCase();return(d==="all"||ex.domain===d)&&(!q||s.includes(q))});if(!list.length){grid.innerHTML='<div class="coach-output">No matching exercises. Try a broader search.</div>';return}list.forEach(ex=>{const card=document.createElement("article");card.className="exercise-card";card.innerHTML=`<div class="card-top"><div><h3>${ex.name}</h3><p>${ex.description}</p></div><span class="badge">${ex.difficulty}</span></div><div class="tags">${ex.targets.map(t=>`<span class="tag">${t}</span>`).join("")}</div><p><strong>Benefits:</strong> ${ex.benefits}</p><details><summary>Instructions, cues and options</summary><ol>${ex.instructions.map(i=>`<li>${i}</li>`).join("")}</ol><p><strong>Coach cues:</strong> ${ex.cues.join(" · ")}</p><p><strong>Common mistakes:</strong> ${ex.mistakes.join(" · ")}</p><p><strong>Gentler:</strong> ${ex.easier}</p><p><strong>Harder:</strong> ${ex.harder}</p></details><div class="card-actions"><button type="button" data-demo="${ex.name}">Show avatar demo</button><button type="button" data-add="${ex.name}">Add to session</button></div>`;grid.appendChild(card)});grid.querySelectorAll("[data-demo]").forEach(b=>b.addEventListener("click",()=>{const ex=exercises.find(x=>x.name===b.dataset.demo);updateAvatar(ex);$("avatarStage").scrollIntoView({behavior:"smooth",block:"center"})}));grid.querySelectorAll("[data-add]").forEach(b=>b.addEventListener("click",()=>{const ex=exercises.find(x=>x.name===b.dataset.add);state.currentPlan.push(planItem(ex,"Main",2,8,45));renderPlan("Custom exercise added.")}))}
function readiness(energy,soreness,experience){let score=55+(energy-3)*10-(soreness-2)*9;if(experience==="starter")score-=4;if(experience==="confident")score+=5;return Math.max(20,Math.min(95,Math.round(score)))}
function handleCoachSubmit(e){e.preventDefault();const ctx={time:+$("timeInput").value,experience:$("experienceInput").value,energy:+$("energyInput").value,soreness:+$("sorenessInput").value,goal:$("goalInput").value,protect:[...document.querySelectorAll("input[name='protect']:checked")].map(x=>x.value)};ctx.readiness=readiness(ctx.energy,ctx.soreness,ctx.experience);state.currentPlan=generatePlan(ctx);renderCoach(ctx);renderPlan("Generated by offline AI Coach.");$("session").scrollIntoView({behavior:"smooth"})}
function generatePlan(ctx){const prefs={balanced:D,strength:[D[0],D[1],D[2]],core:[D[2],D[3],D[5]],mobility:[D[3],D[2],D[0]],cardio:[D[4],D[5],D[3]]}[ctx.goal];const mainCount=ctx.time<=10?3:ctx.time<=20?4:ctx.time<=30?5:6;const intensity=ctx.readiness<45?"gentle":ctx.readiness>74?"strong":"standard";const sets=intensity==="gentle"?1:intensity==="standard"?2:3;const reps=ctx.experience==="starter"?6:ctx.experience==="building"?8:10;const rest=intensity==="gentle"?60:intensity==="standard"?45:35;let pool=exercises.filter(ex=>prefs.includes(ex.domain));if(ctx.protect.length)pool=pool.filter(ex=>!ex.protect.some(p=>ctx.protect.includes(p))||ex.difficulty==="Starter");if(ctx.experience==="starter")pool=pool.filter(ex=>ex.difficulty!=="Confident");if(ctx.readiness<45)pool=pool.filter(ex=>ex.difficulty==="Starter"||ex.domain===D[3]);const selected=[];for(const d of prefs){const choices=pool.filter(ex=>ex.domain===d&&!selected.includes(ex));if(choices.length&&selected.length<mainCount)selected.push(choices[Math.floor(Math.random()*choices.length)])}while(selected.length<mainCount&&pool.length){const ex=pool[Math.floor(Math.random()*pool.length)];if(!selected.includes(ex))selected.push(ex);if(selected.length>=pool.length)break}const warm=exercises.find(ex=>ex.name===(ctx.goal==="cardio"?"March in Place":"Cat-Cow"));const cool=exercises.find(ex=>ex.name==="Thoracic Rotation");return[planItem(warm,"Warm-up",1,ctx.goal==="cardio"?60:6,20),...selected.slice(0,mainCount).map(ex=>planItem(ex,"Main",sets,reps,rest,ctx.protect)),planItem(cool,"Cooldown",1,5,20)]}
function planItem(ex,phase,sets,reps,rest,protect=[]){const mod=protect.some(p=>ex.protect.includes(p))?`Use gentler option: ${ex.easier}`:ex.easier;return{phase,name:ex.name,domain:ex.domain,difficulty:ex.difficulty,pattern:ex.pattern,targets:ex.targets,sets,reps,rest,cues:ex.cues,benefits:ex.benefits,modification:mod,harder:ex.harder}}
function renderCoach(ctx){const tone=ctx.readiness<45?"Recovery-biased":ctx.readiness>74?"Higher-readiness":"Steady";$("coachOutput").innerHTML=`<h3>Today’s AI coach view</h3><div class="score">${ctx.readiness}</div><p><strong>${tone} session.</strong> Energy ${ctx.energy}/5 and soreness ${ctx.soreness}/5 suggest ${ctx.readiness<45?"shorter sets, more rest and mobility-first choices":ctx.readiness>74?"a slightly stronger plan while keeping form quality first":"a balanced plan with moderate rest and controlled progressions"}.</p><p><strong>Protected areas:</strong> ${ctx.protect.length?ctx.protect.join(", "):"none selected"}. The coach avoids or modifies higher-load patterns that may irritate those areas.</p><p><strong>Important:</strong> This is not medical advice. Stop for pain, dizziness, chest discomfort, faintness or unusual shortness of breath.</p>`}
function renderPlan(note=""){const wrap=$("sessionPlan");if(!state.currentPlan.length){wrap.textContent="No session generated yet.";wrap.classList.add("empty");return}wrap.classList.remove("empty");wrap.innerHTML=`<p>${note}</p><div class="plan-list">${state.currentPlan.map(i=>`<div class="plan-item"><strong>${i.phase}: ${i.name}</strong><small>${i.domain} · ${i.targets.join(", ")}</small><small>${i.sets} set(s) · ${i.reps} reps/seconds · ${i.rest}s rest</small><small><strong>Cues:</strong> ${i.cues.join(" · ")}</small><small><strong>Gentler option:</strong> ${i.modification}</small></div>`).join("")}</div>`}
function planText(){if(!state.currentPlan.length)return"No session generated yet.";return`# Avatar Bodyweight Coach Session\n\nGenerated locally on ${new Date().toLocaleString()}\n\n`+state.currentPlan.map(i=>`## ${i.phase}: ${i.name}\n- Domain: ${i.domain}\n- Body parts trained: ${i.targets.join(", ")}\n- Dose: ${i.sets} set(s), ${i.reps} reps/seconds, ${i.rest}s rest\n- Cues: ${i.cues.join("; ")}\n- Gentler option: ${i.modification}\n- Harder option: ${i.harder}\n`).join("\n")}
async function copyPlan(){await navigator.clipboard.writeText(planText());$("copyPlanBtn").textContent="Copied";setTimeout(()=>$("copyPlanBtn").textContent="Copy plan",1200)}
function downloadPlan(){downloadFile("avatar-bodyweight-session.md",planText(),"text/markdown")}
function handleLogSubmit(e){e.preventDefault();state.logs.unshift({date:new Date().toISOString(),minutes:+$("logMinutes").value,effort:$("logEffort").value,note:$("logNote").value.trim()});localStorage.setItem("abc_logs",JSON.stringify(state.logs));$("logNote").value="";renderProgress()}
function renderProgress(){const total=state.logs.reduce((s,e)=>s+Number(e.minutes||0),0),recent=state.logs.slice(0,8);$("progressSummary").innerHTML=`<p><strong>${state.logs.length}</strong> session(s) logged · <strong>${total}</strong> total minute(s).</p>${recent.length?`<table class="progress-table"><thead><tr><th>Date</th><th>Minutes</th><th>Effort</th><th>Note</th></tr></thead><tbody>${recent.map(e=>`<tr><td>${new Date(e.date).toLocaleDateString()}</td><td>${e.minutes}</td><td>${e.effort}</td><td>${e.note||"—"}</td></tr>`).join("")}</tbody></table>`:`<p>No sessions logged yet.</p>`}`}
function exportLog(){const header="date,minutes,effort,note\n",rows=state.logs.map(e=>[e.date,e.minutes,e.effort,`"${String(e.note||"").replace(/"/g,'""')}"`].join(",")).join("\n");downloadFile("avatar-bodyweight-log.csv",header+rows,"text/csv")}
function clearLog(){if(!confirm("Clear local progress log?"))return;state.logs=[];localStorage.removeItem("abc_logs");renderProgress()}
function downloadFile(filename,content,type){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}
init();